### ISSUE TITLE
Codespaces default image missing libbz2-dev

### ISSUE THREAD

**Issue by cl1ent** [microsoft/vscode-dev-containers#1006]
Hi,

I'm currently testing the new codespaces feature for a Python project and encountered the following error:
After having installed `pandas` via pypi and trying to import (`import pandas as pd`) it, I get the error message:
```error: ModuleNotFoundError: No module named '_bz2'```

Installing `libbz2-dev` via a sudo apt-get followed by copying `/usr/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so` to the `/workspaces/$PROJECTNAME/.venv/lib/python3.8/site-packages/` folder helped.
I see that in https://github.com/microsoft/vscode-dev-containers/blob/main/containers/codespaces-linux/.devcontainer/library-scripts/python-debian.sh libbz2 gets installed if Python is installed from source, but otherwise I wonder why it's missing when installing from PPA.

- VSCode Version: latest codespaces version
- Local OS Version: Win 10 Version 21H1 (should not matter)
- Reproduces in: Codespaces
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1. Open Python repository
2. Create new workspace from repository
3. Wait for automated setup & installs
4. Enter virtualenv (not sure why the default terminal does not have the venv activated by default..)
5. Open python
6. Try `import pandas as pd`

Maybe someone has an idea, would be much appreciated. A quick fix would be to create my own image or define a non-PPA Python version in my config file I guess.

Best,
cl1ent

**Comment by Chuxel** [comment]
@cl1ent Is this in the default codespaces image? (A PPA is not used to install there is why I ask.)

//cc: @joshspicer

**Comment by cl1ent** [comment]
@Chuxel yes, I have not selected a specific version or have a `devcontainer.json` file. do you have a way to confirm this within codespaces? CTRL+Shift+P and running "Codespaces: Details" does not reveal much information on the used image etc.

**Comment by Chuxel** [comment]
You can open a terminal and type `devcontainer-info` to get details about what you are using. Given what you describe, I'm assuming the `Definition ID` field will say `codespaces-linux`.

**Comment by cl1ent** [comment]
Yes, indeed

```
Development container image information

- Image version: 1.6.3
- Definition ID: codespaces-linux
- Source code repository: https://github.com/microsoft/vscode-dev-containers/
- Source code release/branch: v0.191.1
- Timestamp: Fri, 13 Aug 2021 23:23:36 GMT
```

**Comment by jkeech** [comment]
+1 on the hit count. Another Codespaces user contacted GitHub Support with this same issue.

**Comment by joshspicer** [comment]
able to repro:
![image](https://user-images.githubusercontent.com/23246594/132911170-a89fc5c9-6f9c-4e98-935b-302db31ae00c.png)

**Comment by jorgeorpinel** [comment]
Hi. I hit the same problem. For me specifically, this prevents the default container's (default) Python from importing package [`dvc`](https://pypi.org/project/dvc/) when installed globally with `pip`.

**Comment by joshspicer** [comment]
@jorgeorpinel - are you sourcing the virtual environment that gets created, or the python install from the `.python` folder?

eg (with no `(venv)` in the prompt):
```
codespace ➜ /workspaces/almost-empty (main ✗) $ which python
/home/codespace/.python/current/bin/python
codespace ➜ /workspaces/almost-empty (main ✗) $ 
```

**Comment by joshspicer** [comment]
![image](https://user-images.githubusercontent.com/23246594/133288244-113dd0fa-5e9d-4749-a9d7-8b0a0a5d1cde.png)

Interestingly, missing some different module when running outside the virtual env (after installing deps).

**Comment by joshspicer** [comment]
issue repros from the [source oryx image](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/codespaces-linux/.devcontainer/base.Dockerfile#L5)

<details>
  <summary>Expand for details</summary>

```
vscode ➜ /workspaces/docker-from-docker (main) $ docker run --rm -it mcr.microsoft.com/oryx/build:vso-focal-20210902.1



root@0ba1d0e7d57f:/vscode-remote-try-python# l
LICENSE  README.md  app.py  disabled.dcont/  requirements.txt  static/
root@0ba1d0e7d57f:/vscode-remote-try-python# git branch
* (HEAD detached at origin/universal-img)
  main
root@0ba1d0e7d57f:/vscode-remote-try-python# oryx build -p virtualenv_name=.venv --log-file /tmp/oryx-build.log --manifest-dir /tmp
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210902.1, Commit: a72ec250bb229f96c55cae8df7800337738fa178, ReleaseTagName: 20210902.1

Build Operation ID: |fIJAPnCTypw=.43209bb8_
Repository Commit : 5bb4d0ddd6c87470130bfd1937128e20839d7845

Detecting platforms...
Detected following platforms:
  python: 3.8.6


Source directory     : /vscode-remote-try-python
Destination directory: /vscode-remote-try-python

Python Version: /opt/python/3.8.6/bin/python3.8
Creating directory for command manifest file if it doesnot exist
Removing existing manifest file
Python Virtual Environment: .venv
Creating virtual environment...
Activating virtual environment...
Running pip install...
[16:10:22+0000] Collecting flask
[16:10:22+0000]   Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
[16:10:23+0000] Collecting pandas
[16:10:23+0000]   Downloading pandas-1.3.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
[16:10:23+0000] Collecting Werkzeug>=2.0
[16:10:23+0000]   Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)
[16:10:23+0000] Collecting Jinja2>=3.0
[16:10:23+0000]   Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
[16:10:23+0000] Collecting itsdangerous>=2.0
[16:10:23+0000]   Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
[16:10:23+0000] Collecting click>=7.1.2
[16:10:23+0000]   Downloading click-8.0.1-py3-none-any.whl (97 kB)
[16:10:23+0000] Collecting pytz>=2017.3
[16:10:23+0000]   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
[16:10:24+0000] Collecting numpy>=1.17.3
[16:10:24+0000]   Downloading numpy-1.21.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
[16:10:24+0000] Collecting python-dateutil>=2.7.3
[16:10:24+0000]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[16:10:24+0000] Collecting MarkupSafe>=2.0
[16:10:24+0000]   Downloading MarkupSafe-2.0.1-cp38-cp38-manylinux2010_x86_64.whl (30 kB)
[16:10:24+0000] Collecting six>=1.5
[16:10:24+0000]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[16:10:24+0000] Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, flask, pytz, numpy, six, python-dateutil, pandas
[16:10:30+0000] Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 Werkzeug-2.0.1 click-8.0.1 flask-2.0.1 itsdangerous-2.0.1 numpy-1.21.2 pandas-1.3.3 python-dateutil-2.8.2 pytz-2021.1 six-1.16.0
WARNING: You are using pip version 20.2.1; however, version 21.2.4 is available.
You should consider upgrading via the '/vscode-remote-try-python/.venv/bin/python -m pip install --upgrade pip' command.
vso-focal
PlatformWithVersion=Python 3.8.6
BuildCommands=/opt/python/3.8.6/bin/python3.8 -m venv .venv --copies --system-site-packages
 ,  , python -m pip install --cache-dir /usr/local/share/pip-cache --prefer-binary -r requirements.txt | ts [%T%z]
Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 12 sec(s).
root@0ba1d0e7d57f:/vscode-remote-try-python# source .venv/
bin/        include/    lib/        lib64/      pyvenv.cfg
root@0ba1d0e7d57f:/vscode-remote-try-python# source .venv/bin/activate
(.venv) root@0ba1d0e7d57f:/vscode-remote-try-python# ls
LICENSE  README.md  app.py  disabled.dcont  requirements.txt  static
(.venv) root@0ba1d0e7d57f:/vscode-remote-try-python# python app.py
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    import pandas as pd
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/core/generic.py", line 122, in <module>
    from pandas.core.describe import describe_ndframe
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/core/describe.py", line 39, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import stringify_path
  File "/vscode-remote-try-python/.venv/lib/python3.8/site-packages/pandas/io/common.py", line 4, in <module>
    import bz2
  File "/opt/python/3.8.6/lib/python3.8/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
(.venv) root@0ba1d0e7d57f:/vscode-remote-try-python#

```

</details>

**Comment by joshspicer** [comment]
Messaging the oryx team for their opinion

cc/ @arroyc

**Comment by joshspicer** [comment]
Change is in PR: https://github.com/microsoft/Oryx/pull/1117/files#diff-e6fb817bdfbad97c81ad38f4f4da12cc1e73ca0eb0f2c47100663d7d020d8b00R28

Pair programmed with Arjun a bit and he walked me through the process for a change like this.  A change to the SDKs that oryx pulls as part of a dynamic installation does NOT require an image bump in our kitchensink image.  

@arroyc will give me the magic signal once the SDK update is live so I can validate.

**Comment by joshspicer** [comment]
Oryx's SDK updates fix specific issue with `pandas`. 

![image](https://user-images.githubusercontent.com/23246594/136074379-a002bdc8-ac21-4691-9f71-eaf287c67615.png)

This will get picked up automatically as this is part of the dynamic installation bit of Oryx.

@jorgeorpinel - please let me know if you're still hitting your problem. As a workaround now you (may) be able to source the dynamically created virtual environment
