### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by stiliajohny** [microsoft/vscode-dev-containers#1438]
- VSCode Version: 1.66
- Local OS Version: MacOS 12.3.1
- Local chip architecture:  Apple Silicon
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: mcr.microsoft.com/vscode/devcontainers/base:ubuntu

Steps to Reproduce:

1. Load the project with the docokerfile that has FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu
2. Allow VScode to build 

If I docker build the docker file, it works 

If I let VSCode doing its things I get the following error 

```log
[2022-05-06T14:26:50.653Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/mhy14/github/crs-secure-image --filter label=vsch.quality=stable
[2022-05-06T14:26:50.741Z] Stop (88 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/mhy14/github/crs-secure-image --filter label=vsch.quality=stable
[2022-05-06T14:26:50.741Z] Start: Run: docker inspect --type container 9be13a4aa2fe
[2022-05-06T14:26:50.811Z] Stop (70 ms): Run: docker inspect --type container 9be13a4aa2fe
[2022-05-06T14:26:50.811Z] Start: Starting container
[2022-05-06T14:26:50.811Z] Start: Run: docker start 9be13a4aa2fe9c525508a70320e6c2a76324ff3d949cc59b9f1a4b2ac42276b1
[2022-05-06T14:26:51.108Z] Stop (297 ms): Run: docker start 9be13a4aa2fe9c525508a70320e6c2a76324ff3d949cc59b9f1a4b2ac42276b1
[2022-05-06T14:26:51.108Z] Stop (297 ms): Starting container
[2022-05-06T14:26:51.108Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/mhy14/github/crs-secure-image --filter label=vsch.quality=stable
[2022-05-06T14:26:51.173Z] Stop (65 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/mhy14/github/crs-secure-image --filter label=vsch.quality=stable
[2022-05-06T14:26:51.173Z] Start: Run: docker inspect --type container 9be13a4aa2fe
[2022-05-06T14:26:51.239Z] Stop (66 ms): Run: docker inspect --type container 9be13a4aa2fe
[2022-05-06T14:26:51.239Z] Start: Inspecting container
[2022-05-06T14:26:51.239Z] Start: Run: docker inspect --type container 9be13a4aa2fe9c525508a70320e6c2a76324ff3d949cc59b9f1a4b2ac42276b1
[2022-05-06T14:26:51.304Z] Stop (65 ms): Run: docker inspect --type container 9be13a4aa2fe9c525508a70320e6c2a76324ff3d949cc59b9f1a4b2ac42276b1
[2022-05-06T14:26:51.304Z] Stop (65 ms): Inspecting container
[2022-05-06T14:26:51.305Z] Start: Run in container: /bin/sh
[2022-05-06T14:26:51.307Z] Start: Run in container: uname -m
[2022-05-06T14:26:51.453Z] x86_64
[2022-05-06T14:26:51.453Z] 
[2022-05-06T14:26:51.453Z] Stop (146 ms): Run in container: uname -m
[2022-05-06T14:26:51.453Z] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2022-05-06T14:26:51.472Z] Stop (167 ms): Run in container: /bin/sh
[2022-05-06T14:26:51.473Z] Shell server terminated (code: 137, signal: null)
[2022-05-06T14:26:51.472Z] Start: Run in container: cat /etc/passwd
[2022-05-06T14:26:51.473Z] Stdin closed!
[2022-05-06T14:26:51.473Z] Error: An error occurred setting up the container.
[2022-05-06T14:26:51.473Z]     at IR (/Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:995)
[2022-05-06T14:26:51.473Z]     at zy (/Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:933)
[2022-05-06T14:26:51.473Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-05-06T14:26:51.473Z]     at async $R (/Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:2007)
[2022-05-06T14:26:51.473Z]     at async Zy (/Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:3112)
[2022-05-06T14:26:51.474Z]     at async BR (/Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12448)
[2022-05-06T14:26:51.474Z]     at async qR (/Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12204)
[2022-05-06T14:26:51.475Z] Stop (90886 ms): Run: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/mhy14/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/mhy14/github/crs-secure-image --workspace-mount-consistency consistent --id-label vsch.local.folder=/Users/mhy14/github/crs-secure-image --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/mhy14/github/crs-secure-image/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-06T14:26:51.476Z] Exit code 1
[2022-05-06T14:26:51.477Z] Command failed: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/mhy14/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/mhy14/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/mhy14/github/crs-secure-image --workspace-mount-consistency consistent --id-label vsch.local.folder=/Users/mhy14/github/crs-secure-image --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/mhy14/github/crs-secure-image/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-06T14:26:51.478Z] Exit code 1
```

**Comment by bamurtaugh** [comment]
@chrmarti should we transfer to remote-release?

**Comment by stiliajohny** [comment]
I believe I have found the issue, or at least it works. 

the default entrypoint ( dind script in this case ) expects to run a command ( as the last command is `exec $` 
If, on the `devcontainer.json` I set `overideCommand:false` then vscode cannot execute the commands ( which are failing ). 
For example, it cannot do `uname -m` or `cat /etc/passwd` 

When I, however set `overideCommand:true` then it works as vscode can execute the pre-fly commands to determine x.y.z attributes


I feel I can close this issue now, however, I feel it is related to the extension as it is an extension setting vs the actual container itself. 


Thanks anyway !!

**Comment by stiliajohny** [comment]
FAO @bamurtaugh @chrmarti

**Comment by chrmarti** [comment]
When adding it as a feature, its entrypoint should be run also when not overriding the command. How are you adding it?
```json
	"features": {
		"docker-in-docker": "latest"
	}
```

**Comment by stiliajohny** [comment]
> When adding it as a feature, its entrypoint should be run also when not overriding the command. How are you adding it?
> 
> ```json
> 	"features": {
> 		"docker-in-docker": "latest"
> 	}
> ```

Adding the script and then `RUN` it
