### ISSUE TITLE
Error when installing .NET CLI on ubuntu machine in codespaces 

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/vscode-dev-containers#1458]
I am getting the below error when trying to install `.NET CLI` on an ubuntu machine in codespaces. Please check below creation log for information. 

I am using below syntax in `devcontainer.json` for adding .NET CLI.
![image](https://user-images.githubusercontent.com/17148381/169474854-207b79be-8d45-46c2-b99f-fa5e60cf438c.png)

```
2022-05-20 06:32:52.331Z: Configuration starting...
2022-05-20 06:32:53.078Z: @microsoft/vscode-dev-containers-cli 0.62.0.
2022-05-20 06:32:53.111Z: Start: Resolving Remote
2022-05-20 06:32:53.123Z: $ /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/docs --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/docs/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe none --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-05-20 06:32:53.190Z: @microsoft/vscode-dev-containers-cli 0.62.0.
2022-05-20 06:32:53.204Z: Start: Resolving Remote
2022-05-20 06:32:53.216Z: $ docker ps -q -a --filter label=Type=codespaces
2022-05-20 06:32:53.245Z: Stop (39 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-05-20 06:32:53.262Z: $ docker build -f /var/lib/docker/codespacemount/workspace/docs/.devcontainer/Dockerfile -t vsc-docs-e0f4c539c4fa64067a232682c3249d54 --build-arg VARIANT=ubuntu-22.04 /var/lib/docker/codespacemount/workspace/docs/.devcontainer
2022-05-20 06:32:53.333Z: #1 [internal] load build definition from Dockerfile
2022-05-20 06:32:53.358Z: #1 sha256:a40b7c166638a13e8062bd9227ba4934372e2833b58563f2155ea87e41512139
2022-05-20 06:32:53.477Z: #1 transferring dockerfile:
2022-05-20 06:32:53.588Z: #1 transferring dockerfile: 617B done
2022-05-20 06:32:53.613Z: #1 DONE 0.3s
2022-05-20 06:32:53.632Z: 
2022-05-20 06:32:53.652Z: #2 [internal] load .dockerignore
2022-05-20 06:32:53.672Z: #2 sha256:a81b50d9920ea4ae5cc4e39f2d3298f12124724a43f9fb84bd4bc15f35d60580
2022-05-20 06:32:53.691Z: #2 transferring context: 2B done
2022-05-20 06:32:53.757Z: #2 DONE 0.3s
2022-05-20 06:32:53.901Z: 
2022-05-20 06:32:53.914Z: #3 [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-22.04
2022-05-20 06:32:53.927Z: #3 sha256:b7c3a93ed1540682933cec7b85ace5974134ce30a109796d21d155ebb7bd8399
2022-05-20 06:32:54.809Z: #3 DONE 0.9s
2022-05-20 06:32:54.825Z: 
2022-05-20 06:32:54.850Z: #4 [1/1] FROM mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-22.04@sha256:1d2c69ebde66dc6fa86b0d88e48660f6795763fe70d4a6be6fc47d7209a65591
2022-05-20 06:32:54.885Z: #4 sha256:e91cde7eccebbc0c1758aa377da866317925b6b0719b2c7c62f8d6ed17396e93
2022-05-20 06:32:54.906Z: #4 resolve mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-22.04@sha256:1d2c69ebde66dc6fa86b0d88e48660f6795763fe70d4a6be6fc47d7209a65591 0.1s done
2022-05-20 06:32:54.944Z: #4 sha256:1d2c69ebde66dc6fa86b0d88e48660f6795763fe70d4a6be6fc47d7209a65591 743B / 743B done
2022-05-20 06:32:54.965Z: #4 sha256:ee1c53071f9c04326860b7e4f33288005fa3e50827ec7aa614cd48a2c93ce010 1.37kB / 1.37kB done
2022-05-20 06:32:54.978Z: #4 sha256:2ffdc8ed695af07c46de4918e917d02872681f55f84a198f224a59a55034b436 3.41kB / 3.41kB done
2022-05-20 06:32:54.990Z: #4 sha256:267116e5ed7e25114cae791a2211cd6d54e09ed17d486b053ee196b0ab35247a 0B / 3.82MB 0.2s
2022-05-20 06:32:55.005Z: #4 sha256:eca1d741d4fb6f7e87293ff74efc9ba1e21413c3597973e423b994995c11f2a1 0B / 3.56MB 0.2s
2022-05-20 06:32:55.057Z: #4 sha256:eca1d741d4fb6f7e87293ff74efc9ba1e21413c3597973e423b994995c11f2a1 3.56MB / 3.56MB 0.3s
2022-05-20 06:32:55.083Z: #4 sha256:8527c5f86ecc162d68a9d38c8f4c6a6443158c67417e8bc2c3cea9f3868394eb 0B / 30.42MB 0.3s
2022-05-20 06:32:55.145Z: #4 sha256:267116e5ed7e25114cae791a2211cd6d54e09ed17d486b053ee196b0ab35247a 3.82MB / 3.82MB 0.4s
2022-05-20 06:32:55.186Z: #4 sha256:eca1d741d4fb6f7e87293ff74efc9ba1e21413c3597973e423b994995c11f2a1 3.56MB / 3.56MB 0.3s done
2022-05-20 06:32:55.206Z: #4 sha256:8527c5f86ecc162d68a9d38c8f4c6a6443158c67417e8bc2c3cea9f3868394eb 6.29MB / 30.42MB 0.4s
2022-05-20 06:32:55.230Z: #4 sha256:35c47d656eff70a864e0d2d4c4e341db63007caa8ea5f11f89a8377aa75d3ec2 0B / 6.03kB 0.4s
2022-05-20 06:32:55.313Z: #4 sha256:267116e5ed7e25114cae791a2211cd6d54e09ed17d486b053ee196b0ab35247a 3.82MB / 3.82MB 0.4s done
2022-05-20 06:32:55.326Z: #4 sha256:8527c5f86ecc162d68a9d38c8f4c6a6443158c67417e8bc2c3cea9f3868394eb 15.73MB / 30.42MB 0.5s
2022-05-20 06:32:55.453Z: #4 sha256:8527c5f86ecc162d68a9d38c8f4c6a6443158c67417e8bc2c3cea9f3868394eb 30.42MB / 30.42MB 0.7s
2022-05-20 06:32:55.550Z: #4 sha256:35c47d656eff70a864e0d2d4c4e341db63007caa8ea5f11f89a8377aa75d3ec2 6.03kB / 6.03kB 0.5s done
2022-05-20 06:32:55.567Z: #4 sha256:734af02d4cbd13316b8e52f9c91cc24fc386de2fbd94209f09ae6b020ca3d284 19.92MB / 89.24MB 0.7s
2022-05-20 06:32:55.592Z: #4 sha256:734af02d4cbd13316b8e52f9c91cc24fc386de2fbd94209f09ae6b020ca3d284 41.05MB / 89.24MB 0.8s
2022-05-20 06:32:55.607Z: 
2022-05-20 06:32:55.761Z: #4 sha256:8527c5f86ecc162d68a9d38c8f4c6a6443158c67417e8bc2c3cea9f3868394eb 30.42MB / 30.42MB 0.8s done
2022-05-20 06:32:55.778Z: #4 sha256:734af02d4cbd13316b8e52f9c91cc24fc386de2fbd94209f09ae6b020ca3d284 75.50MB / 89.24MB 1.0s
2022-05-20 06:32:55.792Z: #4 extracting sha256:8527c5f86ecc162d68a9d38c8f4c6a6443158c67417e8bc2c3cea9f3868394eb
2022-05-20 06:32:55.845Z: #4 sha256:734af02d4cbd13316b8e52f9c91cc24fc386de2fbd94209f09ae6b020ca3d284 84.93MB / 89.24MB 1.1s
2022-05-20 06:32:56.297Z: #4 sha256:734af02d4cbd13316b8e52f9c91cc24fc386de2fbd94209f09ae6b020ca3d284 89.24MB / 89.24MB 1.4s done
2022-05-20 06:32:56.688Z: #4 extracting sha256:8527c5f86ecc162d68a9d38c8f4c6a6443158c67417e8bc2c3cea9f3868394eb 0.9s done
2022-05-20 06:32:56.829Z: #4 extracting sha256:267116e5ed7e25114cae791a2211cd6d54e09ed17d486b053ee196b0ab35247a 0.1s
2022-05-20 06:32:57.193Z: #4 extracting sha256:267116e5ed7e25114cae791a2211cd6d54e09ed17d486b053ee196b0ab35247a 0.3s done
2022-05-20 06:32:57.641Z: #4 extracting sha256:eca1d741d4fb6f7e87293ff74efc9ba1e21413c3597973e423b994995c11f2a1
2022-05-20 06:32:57.781Z: #4 extracting sha256:eca1d741d4fb6f7e87293ff74efc9ba1e21413c3597973e423b994995c11f2a1 0.1s done
2022-05-20 06:32:57.948Z: #4 extracting sha256:35c47d656eff70a864e0d2d4c4e341db63007caa8ea5f11f89a8377aa75d3ec2 done
2022-05-20 06:32:58.228Z: #4 extracting sha256:734af02d4cbd13316b8e52f9c91cc24fc386de2fbd94209f09ae6b020ca3d284 0.1s
2022-05-20 06:33:01.140Z: #4 extracting sha256:734af02d4cbd13316b8e52f9c91cc24fc386de2fbd94209f09ae6b020ca3d284 3.0s done
2022-05-20 06:33:03.212Z: #4 DONE 8.4s
2022-05-20 06:33:03.230Z: 
2022-05-20 06:33:03.249Z: #5 exporting to image
2022-05-20 06:33:03.268Z: #5 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
2022-05-20 06:33:03.298Z: #5 exporting layers done
2022-05-20 06:33:03.325Z: #5 writing image sha256:e0c135063c714c011844fd1b75562473a26109d9d11def9d200ba8f76565ce6e 0.0s done
2022-05-20 06:33:03.362Z: #5 naming to docker.io/library/vsc-docs-e0f4c539c4fa64067a232682c3249d54 0.0s done
2022-05-20 06:33:03.381Z: #5 DONE 0.1s
2022-05-20 06:33:03.402Z: Stop (10128 ms): Run: docker build -f /var/lib/docker/codespacemount/workspace/docs/.devcontainer/Dockerfile -t vsc-docs-e0f4c539c4fa64067a232682c3249d54 --build-arg VARIANT=ubuntu-22.04 /var/lib/docker/codespacemount/workspace/docs/.devcontainer
2022-05-20 06:33:03.420Z: Preparing to parse declared features and fetch remote features.
2022-05-20 06:33:03.433Z: Detected local feature set. Continuing...
2022-05-20 06:33:03.446Z: $ docker inspect --type image vsc-docs-e0f4c539c4fa64067a232682c3249d54
2022-05-20 06:33:03.459Z: Stop (40 ms): Run: docker inspect --type image vsc-docs-e0f4c539c4fa64067a232682c3249d54
2022-05-20 06:33:03.472Z: local container features stored at: /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node_modules/vscode-dev-containers/container-features
2022-05-20 06:33:03.485Z: $ tar --no-same-owner -x -f -
2022-05-20 06:33:03.500Z: Stop (31 ms): Run: tar --no-same-owner -x -f -
2022-05-20 06:33:03.516Z: $ docker build -t vsc-docs-e0f4c539c4fa64067a232682c3249d54-features --build-arg BASE_IMAGE=vsc-docs-e0f4c539c4fa64067a232682c3249d54 --build-arg IMAGE_USER=root /tmp/vsch/container-features/0.62.0-1653028383350
2022-05-20 06:33:03.717Z: #1 [internal] load build definition from Dockerfile
2022-05-20 06:33:03.736Z: #1 sha256:38ba005abd91589b7ecf9186863bc0de005a77d271c2cc3fbf7a17eef62e1ef7
2022-05-20 06:33:03.776Z: #1 transferring dockerfile: 360B done
2022-05-20 06:33:03.857Z: #1 DONE 0.3s
2022-05-20 06:33:03.877Z: 
2022-05-20 06:33:03.901Z: #2 [internal] load .dockerignore
2022-05-20 06:33:03.921Z: #2 sha256:cbe984840a6bb6deb4e632d1d606fd3485a650f161353f5dfd72a00189003fee
2022-05-20 06:33:03.941Z: #2 transferring context: 2B done
2022-05-20 06:33:03.969Z: #2 DONE 0.3s
2022-05-20 06:33:03.988Z: 
2022-05-20 06:33:04.008Z: #3 [internal] load metadata for docker.io/library/vsc-docs-e0f4c539c4fa64067a232682c3249d54:latest
2022-05-20 06:33:04.037Z: #3 sha256:3c78f836b7017f0cafa24f3b20a322fe68bea4363c949644b2390814285cdecc
2022-05-20 06:33:04.081Z: #3 DONE 0.0s
2022-05-20 06:33:04.098Z: 
2022-05-20 06:33:04.122Z: #4 [1/3] FROM docker.io/library/vsc-docs-e0f4c539c4fa64067a232682c3249d54
2022-05-20 06:33:04.141Z: #4 sha256:48bc8fe8dacb48de259830fc76f88f6c2a139805883aa7f263783ece9f17090b
2022-05-20 06:33:04.162Z: #4 CACHED
2022-05-20 06:33:04.181Z: 
2022-05-20 06:33:04.201Z: #5 [internal] load build context
2022-05-20 06:33:04.226Z: #5 sha256:5ebfdfefdc6ddcac27caf785bfdf2382913ca338e6d28fc421bb198aa2a6cef6
2022-05-20 06:33:04.268Z: #5 transferring context: 269.04kB done
2022-05-20 06:33:04.285Z: #5 DONE 0.2s
2022-05-20 06:33:04.301Z: 
2022-05-20 06:33:04.315Z: #6 [2/3] COPY . /tmp/build-features/
2022-05-20 06:33:04.334Z: #6 sha256:872ee91818a96ac71bb5cd4beec1362f62b3333db834499eb4fb3ca204e5838a
2022-05-20 06:33:04.472Z: #6 DONE 0.3s
2022-05-20 06:33:04.612Z: 
2022-05-20 06:33:04.632Z: #7 [3/3] RUN cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh
2022-05-20 06:33:04.654Z: #7 sha256:e88ebc2090fba12da066fcb4a989ac368c62a2ec9089978d38e1eae042bb9a2a
2022-05-20 06:33:05.481Z: #7 0.988 (*) Script: dotnet-debian.sh latest false automatic true /usr/local/dotnet dotnet
2022-05-20 06:33:05.621Z: #7 0.999 (*) Installing .NET CLI...
2022-05-20 06:33:05.636Z: #7 1.007 Running apt-get update...
2022-05-20 06:33:06.068Z: #7 1.583 Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
2022-05-20 06:33:06.237Z: #7 1.666 Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
2022-05-20 06:33:06.796Z: #7 2.314 Get:3 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4653 B]
2022-05-20 06:33:07.105Z: #7 2.478 Get:4 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [64.8 kB]
2022-05-20 06:33:07.119Z: #7 2.543 Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [100.0 kB]
2022-05-20 06:33:07.244Z: #7 2.662 Get:6 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [132 kB]
2022-05-20 06:33:07.552Z: #7 2.961 Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
2022-05-20 06:33:07.861Z: #7 3.265 Get:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
2022-05-20 06:33:08.168Z: #7 3.562 Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
2022-05-20 06:33:08.924Z: #7 4.291 Get:10 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
2022-05-20 06:33:08.953Z: 
2022-05-20 06:33:08.966Z: #7 4.314 Get:11 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
2022-05-20 06:33:10.408Z: #7 5.854 Get:12 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
2022-05-20 06:33:10.480Z: #7 5.856 Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [132 kB]
2022-05-20 06:33:10.493Z: #7 5.858 Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [4653 B]
2022-05-20 06:33:10.505Z: #7 5.858 Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [107 kB]
2022-05-20 06:33:10.519Z: #7 5.859 Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [195 kB]
2022-05-20 06:33:10.532Z: 
2022-05-20 06:33:10.545Z: #7 5.862 Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [1202 B]
2022-05-20 06:33:11.304Z: #7 6.740 Fetched 21.0 MB in 6s (3682 kB/s)
2022-05-20 06:33:11.319Z: #7 6.740 Reading package lists...
2022-05-20 06:33:11.864Z: 
2022-05-20 06:33:12.032Z: #7 7.438 Reading package lists...
2022-05-20 06:33:12.620Z: 
2022-05-20 06:33:12.635Z: #7 8.074 Building dependency tree...
2022-05-20 06:33:12.757Z: 
2022-05-20 06:33:12.773Z: #7 8.265 Reading state information...
2022-05-20 06:33:12.896Z: 
2022-05-20 06:33:12.998Z: #7 8.345 E: Unable to locate package libssl1.1
2022-05-20 06:33:13.028Z: #7 8.345 E: Couldn't find any package by glob 'libssl1.1'
2022-05-20 06:33:13.051Z: #7 8.345 E: Couldn't find any package by regex 'libssl1.1'
2022-05-20 06:33:13.093Z: #7 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh]: exit code: 100
2022-05-20 06:33:13.107Z: ------
2022-05-20 06:33:13.133Z:  > [3/3] RUN cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh:
2022-05-20 06:33:13.154Z: ------
2022-05-20 06:33:13.172Z: executor failed running [/bin/sh -c cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh]: exit code: 100
2022-05-20 06:33:13.201Z: Stop (9637 ms): Run: docker build -t vsc-docs-e0f4c539c4fa64067a232682c3249d54-features --build-arg BASE_IMAGE=vsc-docs-e0f4c539c4fa64067a232682c3249d54 --build-arg IMAGE_USER=root /tmp/vsch/container-features/0.62.0-1653028383350
2022-05-20 06:33:13.225Z: Error: Command failed: docker build -t vsc-docs-e0f4c539c4fa64067a232682c3249d54-features --build-arg BASE_IMAGE=vsc-docs-e0f4c539c4fa64067a232682c3249d54 --build-arg IMAGE_USER=root /tmp/vsch/container-features/0.62.0-1653028383350
2022-05-20 06:33:13.281Z:     at IR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:221:995)
2022-05-20 06:33:13.312Z:     at zy (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:221:933)
2022-05-20 06:33:13.337Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-05-20 06:33:13.357Z:     at async $R (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:226:2007)
2022-05-20 06:33:13.375Z:     at async Zy (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:226:3112)
2022-05-20 06:33:13.419Z:     at async BR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:226:12448)
2022-05-20 06:33:13.438Z:     at async qR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:226:12204)
2022-05-20 06:33:13.457Z: Stop (20021 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/docs --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/docs/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe none --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-05-20 06:33:13.477Z: Exit code 1
2022-05-20 06:33:13.497Z: Failed to create container.
2022-05-20 06:33:13.521Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/docs --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/docs/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe none --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-05-20 06:33:13.541Z: Error Code: 1302
2022-05-20 06:33:13.559Z: Container creation failed.
2022-05-20 06:33:13.578Z: 
2022-05-20 06:33:13.598Z: Creating recovery container.

```

**Comment by jkeech** [comment]
```
2022-05-20 06:33:12.998Z: #7 8.345 E: Unable to locate package libssl1.1
2022-05-20 06:33:13.028Z: #7 8.345 E: Couldn't find any package by glob 'libssl1.1'
2022-05-20 06:33:13.051Z: #7 8.345 E: Couldn't find any package by regex 'libssl1.1'
2022-05-20 06:33:13.093Z: #7 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh]: exit code: 100
```

That seems to be the important part of the log file. @joshspicer, can we update the `dotnet` feature to install needed native dependencies including `libssl`?

**Comment by joshspicer** [comment]
This is probably due to trying to build on top of ubuntu 22.04 (jammy).  As an immediate workaround, I suspect it would work on a previously LTS build of Ubuntu.  That said, definitely something we need to fix - thanks for the issue :)

**Comment by joshspicer** [comment]
relevant: https://github.com/dotnet/sdk/issues/24759

**Comment by joshspicer** [comment]
looks like `jammy` ships with libssl 3.0, which is _supposed_ to work with dotnet 6. However, sounds like the dotnet team is not backporting support for dotnet 5.0 and 3.1 to jammy (due to  libssl 1.1 not shipping with jammy).

ref: https://github.com/dotnet/core/issues/7038#issuecomment-1110377345
