### ISSUE TITLE
python-3-anaconda container fails to build?

### ISSUE THREAD

**Issue by labenz** [microsoft/vscode-dev-containers#1533]
I'm relatively new to vscode-dev-containers, so apologies if this is a rookie mistake on my part, but... I've been using the [python-3-anaconda](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/python-3-anaconda) container in a codespace since May 20, and suddenly this week, the container will not rebuild for me.  

I've rebuilt numerous times, and I have a built version from a few weeks ago that still works normally, but trying to build a new container at this point fails.  

The creation-log is showing the following error content before failing and failing over to recovery mode.

I've tried using an older semantic version (FROM mcr.microsoft.com/vscode/devcontainers/anaconda:0.202.6-3), which seems to have been the latest version when I started using this, but... no luck there either

Any pointers would be appreciated!  

```
2022-07-13 15:00:18.027Z: #18 180.3 (*) Script: jupyterlab-debian.sh latest
2022-07-13 15:00:18.040Z: #18 180.4 Installing JupyterLab...
2022-07-13 15:00:18.058Z: #18 180.5 sudo: python: command not found
2022-07-13 15:00:18.072Z: #18 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh]: exit code: 1
2022-07-13 15:00:18.088Z: ------
2022-07-13 15:00:18.099Z:  > [stage-1 2/2] RUN cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh:
2022-07-13 15:00:18.114Z: 
2022-07-13 15:00:18.125Z: #18 178.5    creating: aws/dist/include/python3.9/
2022-07-13 15:00:18.136Z: #18 178.5   inflating: aws/dist/include/python3.9/pyconfig.h  
2022-07-13 15:00:18.156Z: #18 178.5    creating: aws/dist/lib/python3.9/
2022-07-13 15:00:18.168Z: #18 178.5    creating: aws/dist/lib/python3.9/config-3.9-x86_64-linux-gnu/
2022-07-13 15:00:18.181Z: #18 178.5   inflating: aws/dist/lib/python3.9/config-3.9-x86_64-linux-gnu/Makefile  
2022-07-13 15:00:18.192Z: #18 180.1 You can now run: /usr/local/bin/aws --version
2022-07-13 15:00:18.203Z: #18 180.3 Done!
2022-07-13 15:00:18.214Z: #18 180.3 (*) Script: jupyterlab-debian.sh latest
2022-07-13 15:00:18.225Z: #18 180.4 Installing JupyterLab...
2022-07-13 15:00:18.236Z: #18 180.5 sudo: python: command not found
2022-07-13 15:00:18.247Z: ------
2022-07-13 15:00:18.258Z: error: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh]: exit code: 1
2022-07-13 15:00:18.270Z: Stop (344431 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/vsch/container-features/0.63.0-1657723984531/Dockerfile-with-features -t vsc-base-codespace-b2ed8f27ce6c6efeea52d41325aa4e52 --build-arg NODE_VERSION=lts/* --build-context dev_containers_feature_content_source=/tmp/vsch/container-features/0.63.0-1657723984531 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=vscode --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/base-codespace
2022-07-13 15:00:18.289Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/vsch/container-features/0.63.0-1657723984531/Dockerfile-with-features -t vsc-base-codespace-b2ed8f27ce6c6efeea52d41325aa4e52 --build-arg NODE_VERSION=lts/* --build-context dev_containers_feature_content_source=/tmp/vsch/container-features/0.63.0-1657723984531 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=vscode --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/base-codespace
2022-07-13 15:00:18.300Z:     at jR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:240:1143)
2022-07-13 15:00:18.310Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-07-13 15:00:18.322Z:     at async Uu (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:239:2142)
2022-07-13 15:00:18.333Z:     at async Jy (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:239:1168)
2022-07-13 15:00:18.343Z:     at async zR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:2006)
2022-07-13 15:00:18.354Z:     at async nb (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:3110)
2022-07-13 15:00:18.365Z:     at async JR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:13046)
2022-07-13 15:00:18.376Z:     at async KR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:12802)
2022-07-13 15:00:18.393Z: Stop (344765 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/base-codespace --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/base-codespace/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-13 15:00:18.405Z: Exit code 1
2022-07-13 15:00:18.416Z: Failed to create container.
2022-07-13 15:00:18.428Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/base-codespace --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/base-codespace/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-13 15:00:18.441Z: Error Code: 1302
2022-07-13 15:00:18.455Z: Container creation failed.
2022-07-13 15:00:18.468Z: 
2022-07-13 15:00:18.481Z: Creating recovery container.

```

**Comment by joshspicer** [comment]
Hello!  You're using [this exact file for your .devcontainer/devcontainer.json in codespaces? ](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3-anaconda/.devcontainer/devcontainer.json)
