### ISSUE TITLE
Reopen in Container fails - Illegal argument: base - v0.275.1

### ISSUE THREAD

**Issue by FaBjE** [microsoft/vscode-dev-containers#1712]
I have this issue on two separate machines now, So I'm opening this bug report.
After the update of the extension to v0.275.1 I'm no longer able to open work spaces/folders in containers.

The error I was able to trace is in the "Extension host" output:
```
2023-02-07 08:43:34.796 [error] Error: Illegal argument: base
	at v (c:\Users\Fabje\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1267)
	at new ei (c:\Users\Fabje\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:44917)
	at Wne (c:\Users\Fabje\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:337:23068)
	at hE (c:\Users\Fabje\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:337:20963)
	at async f (c:\Users\Fabje\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:337:9132)
	at async s.h (c:\Users\Fabje\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108008) remote-containers.reopenInContainer {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}

```

My code is located in my WSL filesystem for performance reasons.
Accessing it from the \\wsl$\Ubuntu\home\ or \\wsl.localhost\Ubuntu\home path makes no difference.

The issue is the same as https://github.com/microsoft/vscode-dev-containers/issues/1711 but unfortunately reinstalling everything from WSL, Ubuntu, Docker-Desktop, VSCode and the extension does not solve my issue.

Pre-release version v0.277.0 has the same behavior
Rolling back to previous versions I was able to trace that the fault is introduced in v0.271.0
v0.270.0 - OK
v0.271.0 - Fails

If I open a container workspace from the "Recent" items list, the container is opened and working.

**Workaround**
Reverting back to v0.270.0 or previous release v0.266.1 'solves' the issue

**System Info**
- VSCode Version: 
Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z (5 days ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
- Local OS Version: (Windows 10) Windows_NT x64 10.0.19045
- Local chip architecture: x86
- Name of Dev Container Definition with Issue: At least two containers, both working fine "standalone". https://github.com/zephyrproject-rtos/docker-image and a custom one.
- Docker Desktop: 4.16.3
- Ubuntu 20.04 (and 22.04 on other machine)

**Steps to Reproduce:**
1. Open workspace or folder in vscode with .devcontainer configuration
2. Click "Reopen in container"
3. Expected: Opening container process | Result: Nothing happens

**Comment by FaBjE** [comment]
Duplicate of https://github.com/microsoft/vscode-dev-containers/issues/7985 and https://github.com/microsoft/vscode-dev-containers/issues/7978

**Comment by FaBjE** [comment]
Fixed with: https://github.com/microsoft/vscode-remote-release/issues/7978#issuecomment-1420415169
