### ISSUE TITLE
git pull fails in remote container

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-dev-containers#244]
- VSCode Version: 1.42.1
- Local OS Version: Ubuntu 19.10

Steps to Reproduce:

I am not sure. Working on it. Posting here for exposure.

```
➜  api-server git:(master) git pull
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/tmp/vscode-remote-containers-298bed45ba497798741c3bdfaaa587a0a48d7175.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Password for 'https://hholst80@github.com': 
➜  api-server git:(master) 
```

**Comment by hholst80** [comment]
OK. There is something injected into my ~/.gitconfig

```
[credential]
        helper = "!f() { /home/ubuntu/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node /tmp/vscode-remote-containers-893a35417abc6190bf6456be78f8cff8d6a58054.js $*; }; f"```

**Comment by hholst80** [comment]
The problem with this approach is that /tmp is in the container whereas the /home directory is a persistent volume. Is there any way to turn of the config injection into gitconfig?
