### ISSUE TITLE
Miniconda image doesn't build

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-dev-containers#37]
On Windows 10 with the latest Insiders and Remote Containers.

It says `AttributeError: 'str' object has no attribute 'copy'` towards the end.

```
Setting up container for folder: c:\devel\vscode-dev-containers\containers\python-3-miniconda
Run: docker build -f c:\devel\vscode-dev-containers\containers\python-3-miniconda\.devcontainer\Dockerfile -t vsc-python-3-miniconda-3f2bbeffbfa57df76fd9141490bb6c13 c:\devel\vscode-dev-containers\containers\python-3-miniconda
Sending build context to Docker daemon  17.41kB
Step 1/9 : FROM continuumio/miniconda3
latest: Pulling from continuumio/miniconda3
e79bb959ec00: Already exists
2a7608a50ae3: Downloading [>                                                  ]  424.6kB/42.05MB
2a7608a50ae3:                                                                   2a7608a50ae3: Downloading [=>                                                 ]  850.6kB/42.05MB
ed7fdbb53a8b: Downloading [>                                                  ]  d7fdbb53a8b: Downloading [>                                                  ] 2a7608a50ae3: Downloading [=>                                                 ]  1.277MB/42.05MB
ed7fdbb53a8b: Downloading [>                                                  ] 2a7608a50ae3: Downloading [==>                                                ]  2.141MB/42.05MB                                                                ed7fdbb53a8b: Downloading [=>                                                 ] 2a7608a50ae3: Downloading [===>                                               ]  2.997MB/42.05MB
ed7fdbb53a8b: Downloading [=>                                                 ] 
2a7608a50ae3: Downloading [====>                                              ] 
 3.849MB/42.05MB
ed7fdbb53a8b: Downloading [=>                                                 ] 
2a7608a50ae3: Downloading [=====>                                             ] 
 4.701MB/42.05MB
ed7fdbb53a8b: Downloading [==>                                                ] 
2a7608a50ae3: Downloading [======>                                            ] 
 5.561MB/42.05MB
2a7608a50ae3: Downloading [=======>                                           ] 
 6.413MB/42.05MB
ed7fdbb53a8b: Downloading [==>                                                ] 
2a7608a50ae3: Downloading [========>                                          ] 
 7.269MB/42.05MB
ed7fdbb53a8b: Downloading [===>                                               ] 
2a7608a50ae3: Downloading [=========>                                         ] 
 8.125MB/42.05MB
ed7fdbb53a8b: Downloading [===>                                               ] 
2a7608a50ae3: Downloading [==========>                                        ] 
 8.973MB/42.05MB
ed7fdbb53a8b: Downloading [====>                                              ] 
2a7608a50ae3: Downloading [===========>                                       ] 
 9.825MB/42.05MB
ed7fdbb53a8b: Downloading [====>                                              ] 
2a7608a50ae3: Downloading [============>                                      ] 
 10.69MB/42.05MB
2a7608a50ae3: Downloading [=============>                                     ] 
 11.53MB/42.05MB
2a7608a50ae3: Downloading [==============>                                    ] 
 12.39MB/42.05MB
ed7fdbb53a8b: Downloading [=====>                                             ] 
2a7608a50ae3: Downloading [===============>                                   ] 
 13.26MB/42.05MB
ed7fdbb53a8b: Downloading [======>                                            ] 
2a7608a50ae3: Downloading [================>                                  ] 
 14.12MB/42.05MB
ed7fdbb53a8b: Downloading [======>                                            ] 
2a7608a50ae3: Downloading [=================>                                 ] 
 14.98MB/42.05MB
ed7fdbb53a8b: Downloading [=======>                                           ] 
2a7608a50ae3: Downloading [==================>                                ] 
 15.83MB/42.05MB
ed7fdbb53a8b: Downloading [=======>                                           ] 
2a7608a50ae3: Downloading [===================>                               ] 
 16.69MB/42.05MB
ed7fdbb53a8b: Downloading [========>                                          ] 
2a7608a50ae3: Downloading [====================>                              ] 
 17.54MB/42.05MB
ed7fdbb53a8b: Downloading [========>                                          ] 
2a7608a50ae3: Downloading [=====================>                             ] 
 18.39MB/42.05MB

2a7608a50ae3: Downloading [======================>                            ] 
 19.25MB/42.05MB
2a7608a50ae3: Downloading [=======================>                           ] 
 20.11MB/42.05MB
2a7608a50ae3: Downloading [========================>                          ] 
 20.96MB/42.05MB
ed7fdbb53a8b: Downloading [==========>                                        ] 
2a7608a50ae3: Downloading [=========================>                         ] 
 21.81MB/42.05MB
ed7fdbb53a8b: Downloading [==========>                                        ] 
2a7608a50ae3: Downloading [==========================>                        ] 
 22.67MB/42.05MB
ed7fdbb53a8b: Downloading [===========>                                       ] 
2a7608a50ae3: Downloading [===========================>                       ] 
 23.52MB/42.05MB
2a7608a50ae3: Downloading [============================>                      ] 
 24.38MB/42.05MB
2a7608a50ae3: Downloading [=============================>                     ] 
 25.23MB/42.05MB
ed7fdbb53a8b: Downloading [============>                                      ] 
2a7608a50ae3: Downloading [===============================>                   ] 
 26.09MB/42.05MB
ed7fdbb53a8b: Downloading [============>                                      ] 
2a7608a50ae3: Downloading [================================>                  ] 
 26.95MB/42.05MB
ed7fdbb53a8b: Downloading [=============>                                     ] 
2a7608a50ae3: Downloading [=================================>                 ] 
 27.82MB/42.05MB
ed7fdbb53a8b: Downloading [=============>                                     ] 
2a7608a50ae3: Downloading [==================================>                ] 
 28.67MB/42.05MB
2a7608a50ae3: Downloading [===================================>               ] 
 29.52MB/42.05MB
2a7608a50ae3:
2a7608a50ae3: Downloading [====================================>              ] 
 30.37MB/42.05MB
2a7608a50ae3: Downloading [=====================================>             ] 
 31.23MB/42.05MB
ed7fdbb53a8b: Downloading [===============>                                   ] 
2a7608a50ae3: Downloading [======================================>            ] 
 32.07MB/42.05MB
ed7fdbb53a8b: Downloading [===============>                                   ] 
2a7608a50ae3: Downloading [=======================================>           ] 
 32.92MB/42.05MB
ed7fdbb53a8b: Downloading [================>                                  ] 
2a7608a50ae3: Downloading [========================================>          ] 
 33.77MB/42.05MB
ed7fdbb53a8b: Downloading [================>                                  ] 
2a7608a50ae3: Downloading [=========================================>         ] 
 35.05MB/42.05MB
ed7fdbb53a8b: Downloading [=================>                                 ] 
2a7608a50ae3: Downloading [==========================================>        ] 
  35.9MB/42.05MB
ed7fdbb53a8b: Downloading [=================>                                 ] 
2a7608a50ae3: Downloading [===========================================>       ] 
 36.76MB/42.05MB
2a7608a50ae3: Downloading [============================================>      ] 
 37.61MB/42.05MB
2a7608a50ae3: Downloading [=============================================>     ] 
 38.47MB/42.05MB
ed7fdbb53a8b: Downloading [==================>                                ] 
2a7608a50ae3: Downloading [==============================================>    ] 
 39.32MB/42.05MB
ed7fdbb53a8b: Downloading [===================>                               ] 
2a7608a50ae3: Downloading [===============================================>   ] 
 40.18MB/42.05MB
2a7608a50ae3: Downloading [================================================>  ] 
 40.61MB/42.05MB
ed7fdbb53a8b: Downloading [===================>                               ] 
ed7fdbb53a8b: Downloading [====================>                              ] 
2a7608a50ae3: Downloading [=================================================> ] 
 41.46MB/42.05MB
2a7608a50ae3: Download complete
ed7fdbb53a8b: Downloading [=====================>                             ] 
ed7fdbb53a8b: Downloading [======================>                            ] 
2a7608a50ae3: Extracting [>                                                  ]  
  426kB/42.05MB
2a7608a50ae3: Extracting [==>                                                ]  
1.704MB/42.05MB
2a7608a50ae3: Extracting [====>                                              ]  
3.408MB/42.05MB
2a7608a50ae3: Extracting [=====>                                             ]  
4.686MB/42.05MB
2a7608a50ae3: Extracting [=======>                                           ]  
5.964MB/42.05MB
ed7fdbb53a8b: Downloading [=========================>                         ] 
2a7608a50ae3: Extracting [========>                                          ]  
7.242MB/42.05MB
ed7fdbb53a8b: Downloading [==========================>                        ] 
2a7608a50ae3: Extracting [==========>                                        ]  
 8.52MB/42.05MB
ed7fdbb53a8b: Downloading [==========================>                        ] 
2a7608a50ae3: Extracting [===========>                                       ]  
9.798MB/42.05MB
ed7fdbb53a8b: Downloading [===========================>                       ] 
ed7fdbb53a8b: Downloading [============================>                      ] 
2a7608a50ae3: Extracting [============>                                      ]  
10.65MB/42.05MB
ed7fdbb53a8b: Downloading [============================>                      ] 
2a7608a50ae3: Extracting [=============>                                     ]  
 11.5MB/42.05MB
2a7608a50ae3: Extracting [===============>                                   ]  
12.78MB/42.05MB
ed7fdbb53a8b: Downloading [=============================>                     ] 
2a7608a50ae3: Extracting [=================>                                 ]  
14.48MB/42.05MB
ed7fdbb53a8b: Downloading [==============================>                    ] 
2a7608a50ae3: Extracting [===================>                               ]  
16.19MB/42.05MB
2a7608a50ae3: Extracting [====================>                              ]  
17.47MB/42.05MB
ed7fdbb53a8b: Downloading [===============================>                   ] 
2a7608a50ae3: Extracting [======================>                            ]  
18.74MB/42.05MB
ed7fdbb53a8b: Downloading [================================>                  ] 
2a7608a50ae3: Extracting [=======================>                           ]  
20.02MB/42.05MB
ed7fdbb53a8b: Downloading [=================================>                 ] 
2a7608a50ae3: Extracting [=========================>                         ]  
21.73MB/42.05MB
ed7fdbb53a8b: Downloading [==================================>                ] 
2a7608a50ae3: Extracting [===========================>                       ]  
   23MB/42.05MB
2a7608a50ae3:
2a7608a50ae3: Extracting [============================>                      ]  
23.86MB/42.05MB
ed7fdbb53a8b: Downloading [====================================>              ] 
2a7608a50ae3: Extracting [=============================>                     ]  
24.71MB/42.05MB
2a7608a50ae3: Extracting [==============================>                    ]  
25.56MB/42.05MB
ed7fdbb53a8b: Downloading [======================================>            ] 
2a7608a50ae3: Extracting [================================>                  ]  
27.26MB/42.05MB
ed7fdbb53a8b: Downloading [=======================================>           ] 
2a7608a50ae3: Extracting [=================================>                 ]  
28.11MB/42.05MB
ed7fdbb53a8b: Downloading [=========================================>         ] 
2a7608a50ae3: Extracting [=================================>                 ]  
28.54MB/42.05MB
2a7608a50ae3: Extracting [==================================>                ]  
29.39MB/42.05MB
2a7608a50ae3: Extracting [====================================>              ]  
30.67MB/42.05MB
2a7608a50ae3: Extracting [=====================================>             ]  
31.95MB/42.05MB
ed7fdbb53a8b: Downloading [============================================>      ] 
2a7608a50ae3: Extracting [========================================>          ]  
33.65MB/42.05MB
ed7fdbb53a8b: Downloading [=============================================>     ] 
2a7608a50ae3: Extracting [=========================================>         ]  
34.93MB/42.05MB
ed7fdbb53a8b: Downloading [==============================================>    ] 
2a7608a50ae3: Extracting [===========================================>       ]  
36.21MB/42.05MB
ed7fdbb53a8b: Downloading [===============================================>   ] 
2a7608a50ae3: Extracting [============================================>      ]  
37.06MB/42.05MB
ed7fdbb53a8b: Downloading [================================================>  ] 
2a7608a50ae3: Extracting [=============================================>     ]  
37.91MB/42.05MB
2a7608a50ae3: Extracting [==============================================>    ]  
2a7608a50ae3: Extracting [===============================================>   ]  
2a7608a50ae3: Extracting [================================================>  ]  
2a7608a50ae3: Extracting [=================================================> ]  
2a7608a50ae3: Extracting [==================================================>]  
2a7608a50ae3: Pull complete
ed7fdbb53a8b: Extracting [>                                                  ]  
ed7fdbb53a8b: Extracting [=>                                                 ]  
ed7fdbb53a8b: Extracting [==>                                                ]  
ed7fdbb53a8b: Extracting [==>                                                ]  
ed7fdbb53a8b: Extracting [===>                                               ]  
ed7fdbb53a8b: Extracting [===>                                               ]  
ed7fdbb53a8b: Extracting [====>                                              ]  
ed7fdbb53a8b: Extracting [=====>                                             ]  
ed7fdbb53a8b: Extracting [=====>                                             ]  
ed7fdbb53a8b: Extracting [======>                                            ]  
ed7fdbb53a8b: Extracting [=======>                                           ]  
ed7fdbb53a8b: Extracting [========>                                          ]  
ed7fdbb53a8b: Extracting [==========>                                        ]  
ed7fdbb53a8b: Extracting [============>                                      ]  
ed7fdbb53a8b: Extracting [=============>                                     ]  
ed7fdbb53a8b: Extracting [===============>                                   ]  
ed7fdbb53a8b: Extracting [=================>                                 ]  
ed7fdbb53a8b: Extracting [==================>                                ]  
ed7fdbb53a8b: Extracting [===================>                               ]  
ed7fdbb53a8b: Extracting [====================>                              ]  
ed7fdbb53a8b: Extracting [=====================>                             ]  
ed7fdbb53a8b: Extracting [======================>                            ]  
ed7fdbb53a8b: Extracting [=======================>                           ]  
ed7fdbb53a8b: Extracting [=======================>                           ]  
ed7fdbb53a8b: Extracting [========================>                          ]  
ed7fdbb53a8b: Extracting [========================>                          ]  
ed7fdbb53a8b: Extracting [=========================>                         ]  
ed7fdbb53a8b: Extracting [==========================>                        ]  
ed7fdbb53a8b: Extracting [===========================>                       ]  
ed7fdbb53a8b: Extracting [============================>                      ]  
ed7fdbb53a8b: Extracting [=============================>                     ]  
ed7fdbb53a8b: Extracting [=============================>                     ]  
ed7fdbb53a8b: Extracting [=============================>                     ]  
ed7fdbb53a8b: Extracting [==============================>                    ]  
ed7fdbb53a8b: Extracting [==============================>                    ]  
ed7fdbb53a8b: Extracting [==============================>                    ]  
ed7fdbb53a8b: Extracting [===============================>                   ]  
 d7fdbb53a8b: Extracting [===============================>                   ]  
ed7fdbb53a8b: Extracting [===============================>                   ]  
ed7fdbb53a8b: Extracting [===============================>                   ]  
ed7fdbb53a8b: Extracting [================================>                  ]  
ed7fdbb53a8b: Extracting [================================>                  ]  
ed7fdbb53a8b: Extracting [=================================>                 ]  
ed7fdbb53a8b: Extracting [=================================>                 ]  
ed7fdbb53a8b: Extracting [=================================>                 ]  
ed7fdbb53a8b: Extracting [==================================>                ]  
ed7fdbb53a8b: Extracting [==================================>                ]  
ed7fdbb53a8b: Extracting [===================================>               ]  
ed7fdbb53a8b: Extracting [===================================>               ]  
ed7fdbb53a8b: Extracting [===================================>               ]  
ed7fdbb53a8b: Extracting [====================================>              ]  
ed7fdbb53a8b: Extracting [=====================================>             ]  
ed7fdbb53a8b: Extracting [======================================>            ]  
ed7fdbb53a8b: Extracting [=======================================>           ]  
ed7fdbb53a8b: Extracting [=========================================>         ]  
ed7fdbb53a8b: Extracting [==========================================>        ]  
ed7fdbb53a8b: Extracting [============================================>      ]  
ed7fdbb53a8b: Extracting [==============================================>    ]  
ed7fdbb53a8b: Extracting [================================================>  ]  
ed7fdbb53a8b: Extracting [=================================================> ]  
ed7fdbb53a8b: Extracting [=================================================> ]  
ed7fdbb53a8b: Extracting [==================================================>]  
ed7fdbb53a8b: Pull complete
d9f5448383b9: Extracting [==================================================>]  
d9f5448383b9: Pull complete
e902202dc40d: Extracting [==================================================>]  
e902202dc40d: Pull complete
Digest: sha256:97c73cf6b1aef82bb9f79d9ee82bdcb7bcef07d508fa270bc608bf61d7e98bec
Status: Downloaded newer image for continuumio/miniconda3:latest
 ---> 6b5cf97566c3
Step 2/9 : COPY .devcontainer/settings.vscode.json /root/.vscode-remote/data/Machine/settings.json
 ---> e4dc523820e4
Step 3/9 : RUN apt-get update && apt-get -y install git procps
 ---> Running in 5c919c51ce76
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [487 kB]
Get:6 http://deb.debian.org/debian stretch-updates/main amd64 Packages [31.7 kB]
Get:7 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Fetched 7907 kB in 6s (1182 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version (1:2.11.0-3+deb9u4).
The following additional packages will be installed:
  libprocps6 psmisc
The following NEW packages will be installed:
  libprocps6 procps psmisc
0 upgraded, 3 newly installed, 0 to remove and 4 not upgraded.
Need to get 431 kB of archives.
After this operation, 1434 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 libprocps6 amd64 2:3.3.12-3+deb9u1 [58.5 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 procps amd64 2:3.3.12-3+deb9u1 [250 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 psmisc amd64 22.21-2.1+b2 [123 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 431 kB in 1s (330 kB/s)
Selecting previously unselected package libprocps6:amd64.
(Reading database ... 10409 files and directories currently installed.)
Preparing to unpack .../libprocps6_2%3a3.3.12-3+deb9u1_amd64.deb ...
Unpacking libprocps6:amd64 (2:3.3.12-3+deb9u1) ...
Selecting previously unselected package procps.
Preparing to unpack .../procps_2%3a3.3.12-3+deb9u1_amd64.deb ...
Unpacking procps (2:3.3.12-3+deb9u1) ...
Selecting previously unselected package psmisc.
Preparing to unpack .../psmisc_22.21-2.1+b2_amd64.deb ...
Unpacking psmisc (22.21-2.1+b2) ...
Setting up psmisc (22.21-2.1+b2) ...
Setting up libprocps6:amd64 (2:3.3.12-3+deb9u1) ...
Setting up procps (2:3.3.12-3+deb9u1) ...
update-alternatives: using /usr/bin/w.procps to provide /usr/bin/w (w) in auto mode
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Removing intermediate container 5c919c51ce76
 ---> b2e9a374f3dd
Step 4/9 : RUN mkdir /workspace
 ---> Running in d1ffff4b18af
Removing intermediate container d1ffff4b18af
 ---> b40d8d8509cb
Step 5/9 : WORKDIR /workspace
 ---> Running in 3360c59961ee
Removing intermediate container 3360c59961ee
 ---> 94639a2e5f8c
Step 6/9 : RUN pip install pylint
 ---> Running in 328e2e53c512
Collecting pylint
  Downloading https://files.pythonhosted.org/packages/60/c2/b3f73f4ac008bef6e75bca4992f3963b3f85942e0277237721ef1c151f0d/pylint-2.3.1-py3-none-any.whl (765kB)
Collecting isort<5,>=4.2.5 (from pylint)
  Downloading https://files.pythonhosted.org/packages/9a/a2/2dc9c43667a5a18c8956dc9c0e771d4e7d69de2c1b2689f2231a7aed7695/isort-4.3.18-py2.py3-none-any.whl (42kB)
Collecting astroid<3,>=2.2.0 (from pylint)
  Downloading https://files.pythonhosted.org/packages/d5/ad/7221a62a2dbce5c3b8c57fd18e1052c7331adc19b3f27f1561aa6e620db2/astroid-2.2.5-py3-none-any.whl (193kB)
Collecting mccabe<0.7,>=0.6 (from pylint)
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from astroid<3,>=2.2.0->pylint) (1.12.0)
Collecting lazy-object-proxy (from astroid<3,>=2.2.0->pylint)
  Downloading https://files.pythonhosted.org/packages/55/08/23c0753599bdec1aec273e322f277c4e875150325f565017f6280549f554/lazy-object-proxy-1.3.1.tar.gz
Collecting typed-ast>=1.3.0; implementation_name == "cpython" (from astroid<3,>=2.2.0->pylint)
  Downloading https://files.pythonhosted.org/packages/17/9e/00918af7bdd616decb5b7ad06a9cd0a4a247d2fccaa630ab448a57e68b98/typed_ast-1.3.5-cp37-cp37m-manylinux1_x86_64.whl (736kB)
Collecting wrapt (from astroid<3,>=2.2.0->pylint)
  Downloading https://files.pythonhosted.org/packages/67/b2/0f71ca90b0ade7fad27e3d20327c996c6252a2ffe88f50a95bba7434eda9/wrapt-1.11.1.tar.gz
Building wheels for collected packages: lazy-object-proxy, wrapt
  Building wheel for lazy-object-proxy (setup.py): started
  Building wheel for lazy-object-proxy (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a0/63/e2/6d93295282cb35b53b14b50b602c76dfb04471e21b31d8ad7b
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/89/67/41/63cbf0f6ac0a6156588b9587be4db5565f8c6d8ccef98202fc
Successfully built lazy-object-proxy wrapt
Installing collected packages: isort, lazy-object-proxy, typed-ast, wrapt, astroid, mccabe, pylint
Successfully installed astroid-2.2.5 isort-4.3.18 lazy-object-proxy-1.3.1 mccabe-0.6.1 pylint-2.3.1 typed-ast-1.3.5 wrapt-1.11.1
Removing intermediate container 328e2e53c512
 ---> 3670f922163f
Step 7/9 : COPY .devcontainer/environment.yml.temp environment.yml* /workspace/
 ---> 51489d809c35
Step 8/9 : RUN if [ -f "environment.yml" ]; then conda env update base -f environment.yml && rm environment.yml*; fi
 ---> Running in 77180b3b1c0d

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/cli/main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/cli/main_update.py", line 69, in execute
        directory=os.getcwd())
      File "/opt/conda/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/opt/conda/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/env.py", line 143, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/env.py", line 129, in from_yaml
        data = validate_keys(data, kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/env.py", line 33, in validate_keys
        new_data = data.copy() if data else {}
    AttributeError: 'str' object has no attribute 'copy'

`$ /opt/conda/bin/conda-env update base -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/opt/conda
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.9.125-linuxkit debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

The command '/bin/sh -c if [ -f "environment.yml" ]; then conda env update base -f environment.yml && rm environment.yml*; fi' returned a non-zero code: 1
Failed: Building an image from the Dockerfile.
Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe build -f c:\devel\vscode-dev-containers\containers\python-3-miniconda\.devcontainer\Dockerfile -t vsc-python-3-miniconda-3f2bbeffbfa57df76fd9141490bb6c13 c:\devel\vscode-dev-containers\containers\python-3-miniconda
```

**Comment by Chuxel** [comment]
@chrmarti Strange - this is new.  Possibly a bug in the miniconda image looking at it.  @qubitron Any idea?

**Comment by qubitron** [comment]
@chrmarti do you have an environment.yml in the workspace root? If so this could be a failure of conda to install the packages.

The container builds fine for me when there is no environment.yml.

**Comment by Chuxel** [comment]
@qubitron Its failing when installing the packages in the environment.yml for the test project so you are probably right.

**Comment by Chuxel** [comment]
So this was a really bad error, but it the yml format was incorrect.  Made a patch, so this is now resolved in master.
