### ISSUE TITLE
Dev Containers on Mac silicon

### ISSUE THREAD

**Issue by mz-zmsoft** [microsoft/vscode-dev-containers#697]
I can not execute any docker command like `Remote-Containers: Reopen in container`

VSCode reports immediately the message **Docker returned an error. Make sure the Docker daemon is running.**

Dev Containers Log
```
[388 ms] Remote-Containers 0.154.1 in VS Code 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480).
[595 ms] Start: Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
[43841 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[43912 ms] spawn docker ENOENT
```

Output when executing docker version manually.
```
docker version --format {{.Server.APIVersion}}
1.41
```

Output in developer tools (hope this helps)
```
console.ts:137 [Extension Host] Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21) (at c (/Users/admin/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:697060))
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn docker ENOENT (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1100:774)
console.ts:137 [Extension Host] stack trace: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21) (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1100:853)
log.ts:197   ERR spawn docker ENOENT: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by Chuxel** [comment]
Docker support on Mac Silicon is still in early stages and so we do not have specific plans or timing on adding support. Marking as a feature request and moving to correct repo.  We also do not have pre-built ARM images. (See #558.)
